<a href="https://colab.research.google.com/github/cennetceylan19/AISummerCamp22/blob/main/MachineLearning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import pandas as pd
import numpy as np 
import seaborn as ns
import matplotlib.pyplot as plt
import xgboost as xgb

In [57]:
from sklearn import datasets
#?datasets ile nasıl kullanıldığını öğrenebiilir hatırlayabiliriz.

In [58]:
iris = datasets.load_iris()

In [59]:
x = iris.data
y = iris.target
#head yazdığımızda hata alırız array halinde datframe değil

In [60]:
print(x)
len(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [61]:
print(y)
len(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


150

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
x_train, x_test, y_train, y_test = train_test_split(x,y, 
                                                    test_size = 0.2, 
                                                    random_state = 42)

In [64]:
x_train.shape

(120, 4)

In [65]:
x_test.shape

(30, 4)

In [66]:
dtrain = xgb.DMatrix(x_train, label = y_train)
dtest = xgb.DMatrix (x_test, label = y_test)

In [67]:
#parametreler dictionary olarak girilir.
#max_depth derinlik karar vermek için sorun sorular olarak düşünülebilir.
#eta iteration sayısı
params = {'max_depth': 3,
          'eta': 0.3,
          'silent':1,
          'number_class': 3}

In [68]:
#tekrar sayısı
num_round = 20

In [69]:
bst = xgb.train(params, dtrain, num_boost_round = num_round)

In [70]:
preds = bst.predict(dtest)

In [71]:
preds

array([1.0714757 , 0.00472507, 1.9689463 , 0.9459836 , 1.2184529 ,
       0.00472507, 0.9949961 , 1.9004917 , 1.2449381 , 1.0071057 ,
       1.8994013 , 0.01416737, 0.00472507, 0.00910392, 0.00472507,
       0.995644  , 2.0111437 , 1.0071057 , 1.0604482 , 2.0177255 ,
       0.00472507, 1.8449394 , 0.00472507, 2.0177255 , 1.9890788 ,
       1.9913728 , 1.9689463 , 1.9890788 , 0.01416737, 0.00910392],
      dtype=float32)

In [72]:
len(preds)


30

In [73]:
preds[:10]

array([1.0714757 , 0.00472507, 1.9689463 , 0.9459836 , 1.2184529 ,
       0.00472507, 0.9949961 , 1.9004917 , 1.2449381 , 1.0071057 ],
      dtype=float32)

In [74]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [82]:
best_preds = np.asarray([np.argmax(line) for line in preds])

In [75]:
from sklearn.metrics import precision_score

In [83]:
precision_score(y_test, best_preds, average='macro')

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.1111111111111111